### ISSUE TITLE
Timestamp in ETProxy

### ISSUE THREAD

**Issue by ghost** [ElephantTracksProject/et2-java#1]
In ETProxy,java, the method flushBuffer is not emitting timestamps.

**Comment by xuanruiqi** [comment]
It isn't! Because I haven't figured out what ought to be a timestamp actually. 
1. ET2 slows program down quite a bit, although not as badly as the old ET. So I don't know if real UNIX timestamps are useful anymore.
2. There are other alternative metrics that serve the function of "time", e.g. allocation counts and/or method entry/exit counts. Currently I don't know which is best.
3. Then, there might be other, perhaps better alternatives, but I haven't come up with any as of yet.

CC'ing @samguyer as he might have more insights into this.

**Comment by ghost** [comment]
Ah ok.  Sounds good. That's fine. I reported this because I saw timestamp in the comments but timestampBuffer wasn't being used :-)

**Comment by greatmazinger** [comment]
Timestamps are logical (allocation count, method counts, etc) and not an actual measure of time.

**Comment by xuanruiqi** [comment]
Thanks @greatmazinger, that's what I thought. Will find a good metric with @samguyer.

**Comment by greatmazinger** [comment]
@xuanruiqi Has this been resolved? (I'm going through the issues to see what's still an issue and what has been resolved. :) )

**Comment by greatmazinger** [comment]
Not sure what needs to be fixed here, so closing this issue.
